workspace:
  base: /go
  path: src/github.com/hvalle/drone-gcs-cache

pipeline:
  deps:
    image: golang:1.10
    pull: true
    commands:
      - go get -u github.com/golang/dep/cmd/dep
      - dep ensure
      - dep status

  test:
    image: golang:1.10
    pull: true
    commands:
      - go vet ./...
      - go test -cover ./...

  build_linux_amd64:
    image: golang:1.10
    pull: true
    group: build
    environment:
      - GOOS=linux
      - GOARCH=amd64
      - CGO_ENABLED=0
    commands:
      - |
        if test "${DRONE_TAG}" = ""; then
          go build -v -ldflags "-X main.build=${DRONE_BUILD_NUMBER}" -a -o release/linux/amd64/drone-gcs-cache
        else
          go build -v -ldflags "-X main.version=${DRONE_TAG##v} -X main.build=${DRONE_BUILD_NUMBER}" -a -o release/linux/amd64/drone-gcs-cache
        fi

  publish_linux_amd64:
    image: plugins/docker:17.12
    pull: true
    secrets: [ docker_username, docker_password ]
    group: docker
    repo: homerovalle/drone-gcs-cache
    auto_tag: true
    dockerfile: Dockerfile
    when:
      event: [ push, tag ]
